apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rorai-tenant/devfile-sample-python-basic/devfile-sample-python-basic@sha256:4b9a4f7604920720b1996b0635692c749d480bed0bd75ad960ed434fde56f48e
        name: my-python
        resources: {}
status: {}
